# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/letters', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # letter. As you add validations to letter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {}
  end

  let(:invalid_attributes) do
    {}
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # lettersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      create_list(:letter, 4)
      get letters_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      letter = create(:letter)
      letter.letter_recipients << create_list(:personal_recipient, 2, letter: letter)
      letter.letter_recipients << create(:coporate_recipient, letter: letter)
      letter.personals << create_list(:personal, 3)
      letter.events << create(:event)
      get letter_url(letter), as: :json
      expect(response).to be_successful
      expect(json[:recipients].count).to eq(3)
      expect(json[:mentions].count).to eq(4)
    end
  end

  describe 'POST /create' do
    it 'creates a new letter' do
      post letters_url, params: { letter: valid_attributes },
                        headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_implemented)
    end
  end

  describe 'PATCH /update' do
    it 'updates the requested letter' do
      letter = create(:letter)
      patch letter_url(letter),
            params: { letter: {} }, headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_implemented)
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested letter' do
      letter = create(:letter)
      delete letter_url(letter), headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_implemented)
    end
  end
end
